language: go

go:
  - 1.20

before_script:
  - echo "Installing dependencies..."
  - go mod tidy
  - go get -v github.com/smartystreets/goconvey
  - go get github.com/go-resty/resty/v2@v2.7.0

script:
  - echo "Running tests..."
  - go test ./... -cover

after_script:
  - echo "Generating coverage report..."
  - go tool cover -html=coverage.out
